org: kkardd
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: "3"
plugins:
    - serverless-dotenv-plugin
    - serverless-plugin-typescript

useDotenv: true

provider:
    name: aws
    runtime: nodejs18.x

functions:
    index:
        handler: src/index.handler
        events:
            - httpApi:
                  path: /
                  method: get
    pay:
        handler: src/pay.pay
        events:
            - httpApi:
                  path: /pay
                  method: post
